###############################################################################
#                         DELIGHT PLUGIN CONFIGURATION                        #
###############################################################################
# Version: 0.1.1-alpha

antigrief:
  # Whether to prevent explosions to affect terrain.
  prevent-explosions: true
  # Whether to cap block entities per chunk (to prevent chunk-bans)
  cap-block-entities: true

block-entities:
  max-block-entities: 100
  max-skulls: 10
  max-banners: 5

messages:
  too-many-entities: '<red>You are only allowed to place no more than <e-max> "<e-type>"s per chunk!'